[Scenario]
Name = "Default Scenario"
OutputPath="output"
OutputType="EXCEL"  # "CSV" (default) | "JSON" | "EXCEL"

[Scenario.Observer]
Type = "MessageObserver"
[Scenario.Observer.Parameters]
IterationFilter = "EveryNumberOfIterations" # "EveryNumberOfIterations" | "EveryElapsedSeconds" | "EveryPercentileOfFinishedIterations"
NumberOfIterations = 10_000
[Scenario.Observer.LogLevelDestinations]
Annealer = "StandardOutput"
Debugging = "Discarded"   # "Discarded"  (Default) | "StandardOutput" | "StandardError"
#Debug = "StandardOutput"
#Model = "StandardOutput"

[Annealer]
Type="Kirkpatrick"
[Annealer.Parameters]
DecisionVariable = "SedimentVsCost"
StartingTemperature = 10_000.0 #10
CoolingFactor =  0.999  # 0.99
MaximumIterations = 1_000_000 # 1M

[Model]
Type = "CatchmentModel"
[Model.Parameters]
BankErosionFudgeFactor = 0.0005     # 5 * 10^(-4) (default)  -- Min = 10^(-4), Max = 5*10^(-4)
WaterDensity = 1.0                  # 1 t/m^3 (default)
LocalAcceleration = 9.81            # 9.81 m/s^2 (default)
GullyCompensationFactor = 0.5       # 0.5 (default)
SedimentDensity = 1.5               # (1.5 t/m^3 default)
SuspendedSedimentProportion = 0.5   # 0.5 (default)
RiparianRevegetationCostPerKilometer = 24000.0 # 24,000 (default)
GullyRestorationCostPerKilometer = 44000.0 # 44,000 (default)
DataSourcePath = "input/Laidley_data_v1_3.xlsx"